### ISSUE TITLE
OSError: no file with expected extension

### ISSUE THREAD

**Issue by mxg007** [yanxp/PointNet#1]
Dear friend:
When I run show3d_balls.py ,there is an error 
Traceback (most recent call last):
  File "C:/Users/123456/Desktop/PointNet/pointnet_pytorch-master_lingzhang1/2.py", line 45, in <module>
    dll=np.ctypeslib.load_library(os.path.join(BASE_DIR, 'render_balls_so'),'.')
  File "F:\anaconda1\lib\site-packages\numpy\ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

**Comment by yanxp** [comment]
@mxg007  hello, you need to compile it again.

**Comment by mxg007** [comment]
Teacher, do you mean to recompile "render_balls_so.cpp"?
